/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "dsp.h"
/* Header for class com_example_dspmanager_DSPforJNI */

#ifndef _Included_com_example_dspmanager_DSPforJNI
#define _Included_com_example_dspmanager_DSPforJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dspmanager_DSPforJNI
 * Method:    DSPfromJNI
 * Signature: ([Ljava/lang/Byte;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_dspmanager_DSPforJNI_DSPfromJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
