/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dsp_convolution_ConvolutionJNI */

#ifndef _Included_dsp_convolution_ConvolutionJNI
#define _Included_dsp_convolution_ConvolutionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dsp_convolution_ConvolutionJNI
 * Method:    convolutionfromJNI
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_dsp_convolution_ConvolutionJNI_convolutionfromJNI
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
